# Generated by Django 5.2.1 on 2025-05-22 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cnpj", models.CharField(max_length=18, unique=True)),
                ("nomeFantasia", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("EMPRESA", "Empresa"), ("CLIENTE", "Cliente")],
                        default="CLIENTE",
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CategoriaServico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_servicos",
                        to="protocolos.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Atendente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atendentes",
                        to="protocolos.empresa",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="endereco",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empresa",
                to="protocolos.endereco",
            ),
        ),
        migrations.CreateModel(
            name="HorarioAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaSemana",
                    models.IntegerField(
                        choices=[
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFim", models.TimeField()),
                (
                    "atendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidade",
                        to="protocolos.atendente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioFuncionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaSemana",
                    models.IntegerField(
                        choices=[
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFim", models.TimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_funcionamento",
                        to="protocolos.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duracaoMinutos", models.PositiveIntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="protocolos.categoriaservico",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="atendente",
            name="especialidades",
            field=models.ManyToManyField(
                related_name="atendentes", to="protocolos.servico"
            ),
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dataHoraInicio", models.DateTimeField()),
                ("dataHoraFim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "atendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.atendente",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.empresa",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.servico",
                    ),
                ),
            ],
        ),
    ]
