# Generated by Django 4.2.20 on 2025-08-21 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email que será usado para login no sistema",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Atendente",
                "verbose_name_plural": "Atendentes",
            },
        ),
        migrations.CreateModel(
            name="CategoriaServico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Categoria de Serviço",
                "verbose_name_plural": "Categorias de Serviços",
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cnpj", models.CharField(max_length=18)),
                ("nomeFantasia", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("rua", models.CharField(max_length=255, verbose_name="Rua")),
                ("numero", models.CharField(max_length=20, verbose_name="Número")),
                ("bairro", models.CharField(max_length=100, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                ("estado", models.CharField(max_length=2, verbose_name="Estado")),
                ("cep", models.CharField(max_length=10, verbose_name="CEP")),
                ("telefone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da organização/empresa", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único (URL amigável)", unique=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "max_empresas",
                    models.PositiveIntegerField(
                        default=5, help_text="Limite de empresas"
                    ),
                ),
                (
                    "max_clientes",
                    models.PositiveIntegerField(
                        default=1000, help_text="Limite de clientes"
                    ),
                ),
                (
                    "max_agendamentos_mes",
                    models.PositiveIntegerField(
                        default=500, help_text="Limite de agendamentos por mês"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuário",
                "verbose_name_plural": "Perfis de Usuários",
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duracaoMinutos", models.PositiveIntegerField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicos",
                        to="protocolos.categoriaservico",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
            },
        ),
        migrations.CreateModel(
            name="HorarioFuncionamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaSemana",
                    models.IntegerField(
                        choices=[
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFim", models.TimeField()),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_funcionamento",
                        to="protocolos.empresa",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Funcionamento",
                "verbose_name_plural": "Horários de Funcionamento",
            },
        ),
        migrations.CreateModel(
            name="HorarioAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diaSemana",
                    models.IntegerField(
                        choices=[
                            (1, "Segunda-feira"),
                            (2, "Terça-feira"),
                            (3, "Quarta-feira"),
                            (4, "Quinta-feira"),
                            (5, "Sexta-feira"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ]
                    ),
                ),
                ("horaInicio", models.TimeField()),
                ("horaFim", models.TimeField()),
                (
                    "atendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidade",
                        to="protocolos.atendente",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Atendimento",
                "verbose_name_plural": "Horários de Atendimento",
            },
        ),
        migrations.AddField(
            model_name="empresa",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("EMPRESA", "Empresa"), ("CLIENTE", "Cliente")],
                        default="CLIENTE",
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("cpf", models.CharField(max_length=14)),
                (
                    "rua",
                    models.CharField(blank=True, max_length=255, verbose_name="Rua"),
                ),
                (
                    "numero",
                    models.CharField(blank=True, max_length=20, verbose_name="Número"),
                ),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=2, verbose_name="Estado"),
                ),
                (
                    "cep",
                    models.CharField(blank=True, max_length=10, verbose_name="CEP"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AddField(
            model_name="categoriaservico",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_servicos",
                to="protocolos.empresa",
            ),
        ),
        migrations.AddField(
            model_name="categoriaservico",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="atendente",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendentes",
                to="protocolos.empresa",
            ),
        ),
        migrations.AddField(
            model_name="atendente",
            name="especialidades",
            field=models.ManyToManyField(
                related_name="atendentes", to="protocolos.servico"
            ),
        ),
        migrations.AddField(
            model_name="atendente",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="atendente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dataHoraInicio", models.DateTimeField()),
                ("dataHoraFim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONFIRMADO", "Confirmado"),
                            ("CANCELADO", "Cancelado"),
                            ("CONCLUIDO", "Concluído"),
                        ],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "atendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.atendente",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agendamentos_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.empresa",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendamentos",
                        to="protocolos.servico",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="protocolos.tenant",
                        verbose_name="Organização",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="atendente",
            unique_together={("tenant", "email")},
        ),
    ]
