# Generated by Django 4.2.20 on 2025-07-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("protocolos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="endereco",
        ),
        migrations.AddField(
            model_name="empresa",
            name="bairro",
            field=models.CharField(
                default="Não informado", max_length=100, verbose_name="Bairro"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="cep",
            field=models.CharField(
                default="00000-000", max_length=10, verbose_name="CEP"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="cidade",
            field=models.CharField(
                default="Não informado", max_length=100, verbose_name="Cidade"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="estado",
            field=models.CharField(default="XX", max_length=2, verbose_name="Estado"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="numero",
            field=models.CharField(default="S/N", max_length=20, verbose_name="Número"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empresa",
            name="rua",
            field=models.CharField(
                default="Não informado", max_length=255, verbose_name="Rua"
            ),
            preserve_default=False,
        ),
    ]
