# Generated by Django 4.2.20 on 2025-07-23 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "protocolos",
            "0002_remove_empresa_endereco_empresa_bairro_empresa_cep_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendamento",
            options={
                "verbose_name": "Agendamento",
                "verbose_name_plural": "Agendamentos",
            },
        ),
        migrations.AlterModelOptions(
            name="atendente",
            options={"verbose_name": "Atendente", "verbose_name_plural": "Atendentes"},
        ),
        migrations.AlterModelOptions(
            name="categoriaservico",
            options={
                "verbose_name": "Categoria de Serviço",
                "verbose_name_plural": "Categorias de Serviços",
            },
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="empresa",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterModelOptions(
            name="endereco",
            options={"verbose_name": "Endereço", "verbose_name_plural": "Endereços"},
        ),
        migrations.AlterModelOptions(
            name="horarioatendimento",
            options={
                "verbose_name": "Horário de Atendimento",
                "verbose_name_plural": "Horários de Atendimento",
            },
        ),
        migrations.AlterModelOptions(
            name="horariofuncionamento",
            options={
                "verbose_name": "Horário de Funcionamento",
                "verbose_name_plural": "Horários de Funcionamento",
            },
        ),
        migrations.AlterModelOptions(
            name="servico",
            options={"verbose_name": "Serviço", "verbose_name_plural": "Serviços"},
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="cnpj",
            field=models.CharField(max_length=18),
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome da organização/empresa", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único (URL amigável)", unique=True
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "max_empresas",
                    models.PositiveIntegerField(
                        default=5, help_text="Limite de empresas"
                    ),
                ),
                (
                    "max_clientes",
                    models.PositiveIntegerField(
                        default=1000, help_text="Limite de clientes"
                    ),
                ),
                (
                    "max_agendamentos_mes",
                    models.PositiveIntegerField(
                        default=500, help_text="Limite de agendamentos por mês"
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Proprietário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="agendamento",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="atendente",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="categoriaservico",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="endereco",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="horarioatendimento",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="horariofuncionamento",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="protocolos.tenant",
                verbose_name="Organização",
            ),
        ),
    ]
