# Generated by Django 4.2.20 on 2025-07-24 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "protocolos",
            "0003_alter_agendamento_options_alter_atendente_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="atendente",
            name="email",
            field=models.EmailField(
                default="temp@exemplo.com",
                help_text="Email que será usado para login no sistema",
                max_length=254,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atendente",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="atendente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="atendente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="atendente",
            unique_together={("tenant", "email")},
        ),
    ]
