# Generated by Django 5.2.1 on 2025-05-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolos', '0004_alter_tiposolicitacao_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Campi'},
        ),
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Servidores'},
        ),
    ]
